<?php

namespace Database\Seeders;

use App\Models\Perfume;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class PerfumeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $perfumes = [
            [
                'name' => 'Ambrato May',
                'brand' => 'Divine Fragrance',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Ambra', 'Resine'],
                'price' => 72.6,
                'description' => 'Una fragranza calda e sofisticata, con note di oud, ambra e resine, perfetta per ogni occasione speciale.',
                'size' => '75ml',
                'image' => 'images/prodotto-1.jpg',
                'ingredients' => ['Alcohol Denat', 'Natural Extracts', 'Parfum'],
                'quantity' => 140,
                'gender' => 'Unisex',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Agreement',
                'brand' => 'Luxe Essence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Gelsomino', 'Peonia', 'Rosa'],
                'price' => 124.59,
                'description' => 'Una fragranza elegante con un cuore floreale e accenti di peonia.',
                'size' => '100ml',
                'image' => 'images/prodotto-2.jpg',
                'ingredients' => ['Natural Extracts', 'Parfum', 'Aqua'],
                'quantity' => 179,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato General',
                'brand' => 'Velvet Perfumes',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Ambra', 'Resine'],
                'price' => 138.19,
                'description' => 'Un profumo avvolgente che unisce la profondità dell`oud alla dolcezza calda dell`ambra',
                'size' => '75ml',
                'image' => 'images/prodotto-3.jpg',
                'ingredients' => ['Essential Oils', 'Parfum', 'Aqua'],
                'quantity' => 132,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Arrive',
                'brand' => 'Luxe Essence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Vaniglia', 'Ambra', 'Patchouli'],
                'price' => 92.04,
                'description' => 'Un bouquet orientale caldo e seducente, arricchito da dolci note di vaniglia, ambra e patchouli.',
                'size' => '50ml',
                'image' => 'images/prodotto-4.jpg',
                'ingredients' => ['Aqua', 'Natural Extracts', 'Parfum'],
                'quantity' => 66,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Teach',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Fiori d`Arancio', 'Rosa', 'Peonia'],
                'price' => 47.79,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '75ml',
                'image' => 'images/prodotto-5.jpg',
                'ingredients' => ['Aqua', 'Essential Oils', 'Parfum'],
                'quantity' => 139,
                'gender' => 'Unisex',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale How',
                'brand' => 'Eterna Scents',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Vaniglia', 'Ambra', 'Muschio'],
                'price' => 105.09,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '50ml',
                'image' => 'images/prodotto-6.jpg',
                'ingredients' => ['Aqua', 'Natural Extracts', 'Parfum'],
                'quantity' => 24,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Hold',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Patchouli', 'Vaniglia', 'Ambra'],
                'price' => 76.72,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '100ml',
                'image' => 'images/prodotto-7.jpg',
                'ingredients' => ['Alcohol Denat', 'Essential Oils', 'Natural Extracts'],
                'quantity' => 143,
                'gender' => 'Donna',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Marino Kid',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Marino',
                'notes' => ['Cedro', 'Sale Marino', 'Brezza Marina'],
                'price' => 134.73,
                'description' => 'Una fragranza fresca e rigenerante, ispirata alla brezza marina e al profumo del mare.',
                'size' => '50ml',
                'image' => 'images/prodotto-8.jpg',
                'ingredients' => ['Alcohol Denat', 'Essential Oils', 'Parfum'],
                'quantity' => 90,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Late',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Patchouli', 'Ambra', 'Vaniglia'],
                'price' => 145.07,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '30ml',
                'image' => 'images/prodotto-9.jpg',
                'ingredients' => ['Parfum', 'Essential Oils', 'Natural Extracts'],
                'quantity' => 31,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Decision',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Ambra', 'Muschio', 'Patchouli'],
                'price' => 78.6,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '100ml',
                'image' => 'images/prodotto-10.jpg',
                'ingredients' => ['Aqua', 'Alcohol Denat', 'Natural Extracts'],
                'quantity' => 147,
                'gender' => 'Donna',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Consumer',
                'brand' => 'Pure Indulgence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Fava Tonka', 'Ambra'],
                'price' => 85.12,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '100ml',
                'image' => 'images/prodotto-11.jpg',
                'ingredients' => ['Alcohol Denat', 'Aqua', 'Essential Oils'],
                'quantity' => 26,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Agrumato Girl',
                'brand' => 'Mystique Aroma',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Agrumato',
                'notes' => ['Limone', 'Mandarino', 'Arancia'],
                'price' => 145.33,
                'description' => 'Un`esplosione di freschezza, con accenti vibranti e frizzanti degli agrumi.',
                'size' => '75ml',
                'image' => 'images/prodotto-12.jpg',
                'ingredients' => ['Parfum', 'Aqua', 'Essential Oils'],
                'quantity' => 173,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Legnoso Run',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Legnoso',
                'notes' => ['Cedro', 'Vetiver', 'Sandalo'],
                'price' => 116.98,
                'description' => 'Un profumo deciso e intenso, con note che richiamano la profondità dei boschi.',
                'size' => '100ml',
                'image' => 'images/prodotto-13.jpg',
                'ingredients' => ['Alcohol Denat', 'Parfum', 'Aqua'],
                'quantity' => 91,
                'gender' => 'Donna',
                'limited_edition' => true,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Fruttato Education',
                'brand' => 'Eterna Scents',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Fruttato',
                'notes' => ['Lampone', 'Prugna', 'Pesca'],
                'price' => 35.67,
                'description' => 'Una fragranza vivace e giocosa, con un mix irresistibile di frutti succosi.',
                'size' => '100ml',
                'image' => 'images/prodotto-14.jpg',
                'ingredients' => ['Aqua', 'Natural Extracts', 'Essential Oils'],
                'quantity' => 177,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Yard',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Rosa', "Fiori d`Arancio", 'Gelsomino'],
                'price' => 72.05,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '30ml',
                'image' => 'images/prodotto-15.jpg',
                'ingredients' => ['Essential Oils', 'Aqua', 'Alcohol Denat'],
                'quantity' => 50,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Speziato Close',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Speziato',
                'notes' => ['Cannella', 'Noce Moscata', 'Zafferano'],
                'price' => 113.3,
                'description' => 'Un mix intrigante e audace di spezie calde, ideale per chi cerca originalità.',
                'size' => '30ml',
                'image' => 'images/prodotto-16.jpg',
                'ingredients' => ['Essential Oils', 'Alcohol Denat', 'Parfum'],
                'quantity' => 10,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Chypré General',
                'brand' => 'Pure Indulgence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Chypré',
                'notes' => ['Bergamotto', 'Quercia', 'Muschio'],
                'price' => 39.88,
                'description' => 'Un connubio elegante di note verdi, legnose e muschiate, per una fragranza senza tempo.',
                'size' => '75ml',
                'image' => 'images/prodotto-17.jpg',
                'ingredients' => ['Essential Oils', 'Parfum', 'Alcohol Denat'],
                'quantity' => 126,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Legnoso Teacher',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Legnoso',
                'notes' => ['Cedro', 'Sandalo', 'Abete'],
                'price' => 76.35,
                'description' => 'Un profumo deciso e intenso, con note che richiamano la profondità dei boschi.',
                'size' => '100ml',
                'image' => 'images/prodotto-18.jpg',
                'ingredients' => ['Aqua', 'Alcohol Denat', 'Parfum'],
                'quantity' => 189,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Situation',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Ambra', 'Muschio', 'Vaniglia'],
                'price' => 46.69,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '50ml',
                'image' => 'images/prodotto-19.jpg',
                'ingredients' => ['Essential Oils', 'Alcohol Denat', 'Parfum'],
                'quantity' => 83,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Agrumato Mission',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Agrumato',
                'notes' => ['Bergamotto', 'Mandarino', 'Limone'],
                'price' => 33.59,
                'description' => 'Un`esplosione di freschezza, con accenti vibranti e frizzanti degli agrumi.',
                'size' => '30ml',
                'image' => 'images/prodotto-20.jpg',
                'ingredients' => ['Aqua', 'Natural Extracts', 'Parfum'],
                'quantity' => 145,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Legnoso Institution',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Legnoso',
                'notes' => ['Abete', 'Sandalo', 'Cedro'],
                'price' => 77.72,
                'description' => 'Un profumo deciso e intenso, con note che richiamano la profondità dei boschi.',
                'size' => '100ml',
                'image' => 'images/prodotto-21.jpg',
                'ingredients' => ['Essential Oils', 'Alcohol Denat', 'Aqua'],
                'quantity' => 103,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Marino Voice',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Marino',
                'notes' => ['Brezza Marina', 'Cedro', 'Alghe'],
                'price' => 136.24,
                'description' => 'Una fragranza fresca e rigenerante, ispirata alla brezza marina e al profumo del mare.',
                'size' => '100ml',
                'image' => 'images/prodotto-22.jpg',
                'ingredients' => ['Natural Extracts', 'Aqua', 'Parfum'],
                'quantity' => 24,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Speziato Recently',
                'brand' => 'Luxe Essence',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Speziato',
                'notes' => ['Cannella', 'Zafferano', 'Noce Moscata'],
                'price' => 43.28,
                'description' => 'Un mix intrigante e audace di spezie calde, ideale per chi cerca originalità.',
                'size' => '100ml',
                'image' => 'images/prodotto-23.jpg',
                'ingredients' => ['Alcohol Denat', 'Aqua', 'Essential Oils'],
                'quantity' => 108,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Agrumato Yourself',
                'brand' => 'Eterna Scents',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Agrumato',
                'notes' => ['Arancia', 'Limone', 'Mandarino'],
                'price' => 108.99,
                'description' => 'Un`esplosione di freschezza, con accenti vibranti e frizzanti degli agrumi.',
                'size' => '30ml',
                'image' => 'images/prodotto-24.jpg',
                'ingredients' => ['Alcohol Denat', 'Aqua', 'Parfum'],
                'quantity' => 67,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Head',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ["Fiori d'Arancio", 'Gelsomino', 'Peonia'],
                'price' => 30.68,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '30ml',
                'image' => 'images/prodotto-25.jpg',
                'ingredients' => ['Parfum', 'Essential Oils', 'Natural Extracts'],
                'quantity' => 88,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Or',
                'brand' => 'Mystique Aroma',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Rosa', 'Peonia', "Fiori d'Arancio"],
                'price' => 129.97,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '30ml',
                'image' => 'images/prodotto-26.jpg',
                'ingredients' => ['Parfum', 'Aqua', 'Natural Extracts'],
                'quantity' => 88,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Agrumato Want',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Agrumato',
                'notes' => ['Limone', 'Mandarino', 'Bergamotto'],
                'price' => 41.34,
                'description' => 'Un`esplosione di freschezza, con accenti vibranti e frizzanti degli agrumi.',
                'size' => '50ml',
                'image' => 'images/prodotto-27.jpg',
                'ingredients' => ['Alcohol Denat', 'Parfum', 'Natural Extracts'],
                'quantity' => 178,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Scientist',
                'brand' => 'Velvet Perfumes',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Fava Tonka', 'Ambra'],
                'price' => 31.21,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '100ml',
                'image' => 'images/prodotto-28.jpg',
                'ingredients' => ['Natural Extracts', 'Alcohol Denat', 'Essential Oils'],
                'quantity' => 72,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Social',
                'brand' => 'Mystique Aroma',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Resine', 'Fava Tonka', 'Ambra'],
                'price' => 46.01,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '100ml',
                'image' => 'images/prodotto-29.jpg',
                'ingredients' => ['Parfum', 'Alcohol Denat', 'Essential Oils'],
                'quantity' => 112,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Fruttato Hear',
                'brand' => 'Luxe Essence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Fruttato',
                'notes' => ['Lampone', 'Pesca', 'Mela Verde'],
                'price' => 61.49,
                'description' => 'Una fragranza vivace e giocosa, con un mix irresistibile di frutti succosi.',
                'size' => '75ml',
                'image' => 'images/prodotto-30.jpg',
                'ingredients' => ['Essential Oils', 'Alcohol Denat', 'Aqua'],
                'quantity' => 40,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Six',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Ambra', 'Muschio', 'Vaniglia'],
                'price' => 36.58,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '50ml',
                'image' => 'images/prodotto-31.jpg',
                'ingredients' => ['Aqua', 'Alcohol Denat', 'Parfum'],
                'quantity' => 43,
                'gender' => 'Uomo',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Fruttato Hand',
                'brand' => 'Divine Fragrance',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Fruttato',
                'notes' => ['Prugna', 'Lampone', 'Pesca'],
                'price' => 63.37,
                'description' => 'Una fragranza vivace e giocosa, con un mix irresistibile di frutti succosi.',
                'size' => '50ml',
                'image' => 'images/prodotto-32.jpg',
                'ingredients' => ['Alcohol Denat', 'Natural Extracts', 'Parfum'],
                'quantity' => 146,
                'gender' => 'Donna',
                'limited_edition' => true,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Agrumato Professional',
                'brand' => 'Divine Fragrance',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Agrumato',
                'notes' => ['Mandarino', 'Arancia', 'Limone'],
                'price' => 93.41,
                'description' => 'Un`esplosione di freschezza, con accenti vibranti e frizzanti degli agrumi.',
                'size' => '100ml',
                'image' => 'images/prodotto-33.jpg',
                'ingredients' => ['Natural Extracts', 'Essential Oils', 'Aqua'],
                'quantity' => 123,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Chypré Lot',
                'brand' => 'Eterna Scents',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Chypré',
                'notes' => ['Bergamotto', 'Quercia', 'Muschio'],
                'price' => 50.82,
                'description' => 'Un connubio elegante di note verdi, legnose e muschiate, per una fragranza senza tempo.',
                'size' => '100ml',
                'image' => 'images/prodotto-34.jpg',
                'ingredients' => ['Aqua', 'Alcohol Denat', 'Parfum'],
                'quantity' => 83,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Marino East',
                'brand' => 'Mystique Aroma',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Marino',
                'notes' => ['Sale Marino', 'Cedro', 'Brezza Marina'],
                'price' => 122.51,
                'description' => 'Una fragranza fresca e rigenerante, ispirata alla brezza marina e al profumo del mare.',
                'size' => '75ml',
                'image' => 'images/prodotto-35.jpg',
                'ingredients' => ['Alcohol Denat', 'Aqua', 'Natural Extracts'],
                'quantity' => 136,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Name',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Peonia', 'Rosa', 'Gelsomino'],
                'price' => 124.4,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '100ml',
                'image' => 'images/prodotto-36.jpg',
                'ingredients' => ['Essential Oils', 'Natural Extracts', 'Parfum'],
                'quantity' => 41,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Trade',
                'brand' => 'Luxe Essence',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Ambra', 'Muschio', 'Vaniglia'],
                'price' => 114.37,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '30ml',
                'image' => 'images/prodotto-37.jpg',
                'ingredients' => ['Natural Extracts', 'Aqua', 'Essential Oils'],
                'quantity' => 116,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Fruttato Hotel',
                'brand' => 'Mystique Aroma',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Fruttato',
                'notes' => ['Pesca', 'Mela Verde', 'Prugna'],
                'price' => 30.09,
                'description' => 'Una fragranza vivace e giocosa, con un mix irresistibile di frutti succosi.',
                'size' => '50ml',
                'image' => 'images/prodotto-38.jpg',
                'ingredients' => ['Natural Extracts', 'Aqua', 'Parfum'],
                'quantity' => 100,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Than',
                'brand' => 'Mystique Aroma',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Ambra', 'Vaniglia', 'Patchouli'],
                'price' => 144.78,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '75ml',
                'image' => 'images/prodotto-39.jpg',
                'ingredients' => ['Alcohol Denat', 'Parfum', 'Natural Extracts'],
                'quantity' => 27,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Orientale Subject',
                'brand' => 'Mystique Aroma',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Orientale',
                'notes' => ['Patchouli', 'Vaniglia', 'Ambra'],
                'price' => 75.17,
                'description' => 'Una fragranza calda e avvolgente, ricca di sfumature esotiche e sensuali.',
                'size' => '30ml',
                'image' => 'images/prodotto-40.jpg',
                'ingredients' => ['Parfum', 'Essential Oils', 'Alcohol Denat'],
                'quantity' => 105,
                'gender' => 'Uomo',
                'limited_edition' => true,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Tonight',
                'brand' => 'Mystique Aroma',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Resine', 'Ambra'],
                'price' => 93.72,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '50ml',
                'image' => 'images/prodotto-41.jpg',
                'ingredients' => ['Natural Extracts', 'Essential Oils', 'Alcohol Denat'],
                'quantity' => 44,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Marino Congress',
                'brand' => 'Luxe Essence',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Marino',
                'notes' => ['Alghe', 'Sale Marino', 'Cedro'],
                'price' => 87.22,
                'description' => 'Una fragranza fresca e rigenerante, ispirata alla brezza marina e al profumo del mare.',
                'size' => '50ml',
                'image' => 'images/prodotto-42.jpg',
                'ingredients' => ['Parfum', 'Natural Extracts', 'Essential Oils'],
                'quantity' => 30,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Floreale Alone',
                'brand' => 'Velvet Perfumes',
                'category' => 'Eau de Parfum',
                'subcategory' => 'Floreale',
                'notes' => ['Peonia', "Fiori d'Arancio", 'Rosa'],
                'price' => 148.26,
                'description' => 'Un profumo delicato e raffinato, con note che evocano la bellezza di un giardino fiorito.',
                'size' => '30ml',
                'image' => 'images/prodotto-43.jpg',
                'ingredients' => ['Natural Extracts', 'Alcohol Denat', 'Aqua'],
                'quantity' => 39,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Speziato Professor',
                'brand' => 'Eterna Scents',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Speziato',
                'notes' => ['Cannella', 'Zafferano', 'Pepe Nero'],
                'price' => 141.91,
                'description' => 'Un mix intrigante e audace di spezie calde, ideale per chi cerca originalità.',
                'size' => '100ml',
                'image' => 'images/prodotto-44.jpg',
                'ingredients' => ['Alcohol Denat', 'Essential Oils', 'Natural Extracts'],
                'quantity' => 128,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Place',
                'brand' => 'Pure Indulgence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Oud', 'Ambra', 'Resine'],
                'price' => 78.34,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '75ml',
                'image' => 'images/prodotto-45.jpg',
                'ingredients' => ['Parfum', 'Aqua', 'Natural Extracts'],
                'quantity' => 41,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Chypré Century',
                'brand' => 'Mystique Aroma',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Chypré',
                'notes' => ['Patchouli', 'Muschio', 'Quercia'],
                'price' => 141.57,
                'description' => 'Un connubio elegante di note verdi, legnose e muschiate, per una fragranza senza tempo.',
                'size' => '50ml',
                'image' => 'images/prodotto-46.jpg',
                'ingredients' => ['Alcohol Denat', 'Essential Oils', 'Aqua'],
                'quantity' => 72,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Fruttato Site',
                'brand' => 'Luxe Essence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Fruttato',
                'notes' => ['Mela Verde', 'Prugna', 'Pesca'],
                'price' => 82.54,
                'description' => 'Una fragranza vivace e giocosa, con un mix irresistibile di frutti succosi.',
                'size' => '50ml',
                'image' => 'images/prodotto-47.jpg',
                'ingredients' => ['Natural Extracts', 'Aqua', 'Parfum'],
                'quantity' => 194,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => false,
                'natural' => true,
                'is_visible' => true,
            ],
            [
                'name' => 'Ambrato Perhaps',
                'brand' => 'Luxe Essence',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Ambrato',
                'notes' => ['Fava Tonka', 'Oud', 'Ambra'],
                'price' => 64.96,
                'description' => 'Un profumo caldo e avvolgente, arricchito dalle note ricche dell`ambra.',
                'size' => '30ml',
                'image' => 'images/prodotto-48.jpg',
                'ingredients' => ['Natural Extracts', 'Alcohol Denat', 'Aqua'],
                'quantity' => 21,
                'gender' => 'Unisex',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Chypré Seem',
                'brand' => 'Mystique Aroma',
                'category' => 'Extrait de Parfum',
                'subcategory' => 'Chypré',
                'notes' => ['Muschio', 'Patchouli', 'Bergamotto'],
                'price' => 34.73,
                'description' => 'Un connubio elegante di note verdi, legnose e muschiate, per una fragranza senza tempo.',
                'size' => '50ml',
                'image' => 'images/prodotto-49.jpg',
                'ingredients' => ['Aqua', 'Essential Oils', 'Parfum'],
                'quantity' => 67,
                'gender' => 'Uomo',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => false,
                'is_visible' => true,
            ],
            [
                'name' => 'Marino Style',
                'brand' => 'Pure Indulgence',
                'category' => 'Eau de Toilette',
                'subcategory' => 'Marino',
                'notes' => ['Alghe', 'Brezza Marina', 'Cedro'],
                'price' => 53.35,
                'description' => 'Una fragranza fresca e rigenerante, ispirata alla brezza marina e al profumo del mare.',
                'size' => '75ml',
                'image' => 'images/prodotto-50.jpg',
                'ingredients' => ['Aqua', 'Natural Extracts', 'Parfum'],
                'quantity' => 177,
                'gender' => 'Donna',
                'limited_edition' => false,
                'vegan' => true,
                'natural' => true,
                'is_visible' => true,
            ],
        ];

        foreach ($perfumes as $perfume) {
            Perfume::create($perfume);
        }
    }
}
